"""Alpha package: SHARED / LIVE-REACHABLE modules plus OFFLINE RESEARCH modules (one namespace).

This package is NOT research-only.  The production DEMO runner (``scripts/demo_trader.py`` ->
``demo.runner`` -> ``demo.opportunity.engine``/``policy``) imports the causal family generators and
their data/cost/session helpers from here.  Nothing in ``alpha`` talks to a broker, RiskPolicy or
execution; research evidence stays bar-level with pessimistic fills.

RULE: a change to a LIVE-REACHABLE module is a PRODUCTION change.  The impact matrix
(``scripts/impact_tests.py``) pulls ``tests/unit/demo`` and the safety overlay for it.  Do not add
research-only dependencies (pandas-heavy search, discovery, ML) to a live-reachable module.

LIVE-REACHABLE (static AST import closure of the production entry points, generated by
``scripts/runtime_import_manifest.py``; kept equal to it by
``tests/unit/alpha/test_boundary_docs.py``).  Includes the ``families`` generators, ``common``
market_data/market_costs/frame/sim/..., ``session``, ``context``, ``regime``, ``signals``,
``timeframe`` and the ``CandidateArrays`` / ``EXIT_TRAIL`` contracts, which currently still live in
``fast/sim.py`` (hence ``fast/__init__.py`` -> ``fast/store.py`` is loaded by the live trader too):

LIVE_REACHABLE_BEGIN
    src/alpha/__init__.py
    src/alpha/common/__init__.py
    src/alpha/common/dataset.py
    src/alpha/common/frame.py
    src/alpha/common/market_costs.py
    src/alpha/common/market_data.py
    src/alpha/common/metrics.py
    src/alpha/common/protocol.py
    src/alpha/common/sim.py
    src/alpha/context/__init__.py
    src/alpha/families/__init__.py
    src/alpha/families/common.py
    src/alpha/families/data.py
    src/alpha/families/eod.py
    src/alpha/families/gap.py
    src/alpha/families/leadlag.py
    src/alpha/families/orb.py
    src/alpha/families/overnight.py
    src/alpha/families/registry.py
    src/alpha/families/roundnum.py
    src/alpha/families/spec.py
    src/alpha/families/structbrk.py
    src/alpha/families/volrev.py
    src/alpha/fast/__init__.py
    src/alpha/fast/sim.py
    src/alpha/fast/store.py
    src/alpha/regime/__init__.py
    src/alpha/session.py
    src/alpha/signals/__init__.py
    src/alpha/signals/candidate.py
    src/alpha/signals/conflicts.py
    src/alpha/signals/evaluation.py
    src/alpha/timeframe/__init__.py
LIVE_REACHABLE_END

RESEARCH-ONLY (never reachable from production; prefixes relative to ``src/alpha/``):

RESEARCH_ONLY_BEGIN
    breakout/
    discovery/
    events/
    formula/
    growth/
    metalabel/
    momentum/
    pullback/
    rawscan/
    strategies/
    temporal/
    registry.py
    common/regime.py
    families/evaluate.py
    families/gate.py
    fast/provider.py
    fast/registry.py
    fast/screen.py
    fast/spec.py
    fast/kernels/
RESEARCH_ONLY_END
"""
